services:
    nginx:
        build: 
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        env_file: ../secrets/.env
        container_name: nginx
        image: nginx
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
    wordpress:
        build: 
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        env_file: ../secrets/.env
        container_name: wordpress
        image: wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        ports:
          - "9000"
        depends_on:
            - mariadb
    mariadb:
        build: 
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        env_file: ../secrets/.env
        container_name: mariadb
        image: mariadb
        restart: on-failure
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        ports:
            - "3306"

volumes:
    wordpress:
         driver: local
         driver_opts:
            type: none
            device: /home/uwywijas/data/wordpress
            o: bind
    mariadb:
         driver: local
         driver_opts:
            type: none
            device: /home/uwywijas/data/mariadb
            o: bind

networks:
    inception:
        name: inception